#!/bin/sh

# Copyright (c) 2016 The Chromic Authors. All rights reserved.

sleep 1

# Prepare to mount storage partition
ROOT_DEV=$(rootdev -s)
# Example root dev types we need to handle: /dev/sda2 -> /dev/sda,
# /dev/mmcblk0p0 -> /dev/mmcblk0p, /dev/ubi2_1 -> /dev/ubi
ROOTDEV_TYPE=$(echo $ROOT_DEV | sed 's/[0-9_]*$//')
STORAGE_DEV=${ROOTDEV_TYPE}1

dbus-send --print-reply --system --dest=org.chromium.CrosDisks /org/chromium/CrosDisks org.chromium.CrosDisks.Mount string:$STORAGE_DEV string:"" array:string:"rw"

